### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jaivalis** [BramBonne/LastfmPlaycount#10]
Is this plugin still maintained? I seem to have an issue enabling it under the most recent build of Rhythmbox.

**Comment by BramBonne** [comment]
Hi John,

I didn't have the time to find out how to get the new Glib/DBus system (which is used in later versions of Rhythmbox) to work, but it should definitely be doable. Feel free to fork my code or submit a patch! I'd be happy to see someone continuing development on this plugin :-)

Kr,
Bram
