### ISSUE TITLE
Plugin not functional in rhythmbox 3.3.1

### ISSUE THREAD

**Issue by kurobeats** [BramBonne/LastfmPlaycount#12]
After install, clicking on "Configure" in the plugins menu the following is thrown

```
Traceback (most recent call last):
  File "/usr/lib/rhythmbox/plugins/lastfmplaycount/lastfmplaycountconfig.py", line 26, in do_create_configure_widget
    builder.add_from_file(rb.find_plugin_file(self, "lastfmplaycount-prefs.ui"))
TypeError: Argument 1 does not allow None as a value

(rhythmbox:25120): libpeas-CRITICAL **: show_configure_cb: assertion 'GTK_IS_WIDGET (conf_widget)' failed
```

**Comment by elzoona** [comment]
Hi @kurobeats , the problem is related to where the plugin store the files (/usr/lib) and where Rhythmbox looks for them (/usr/share), at least the plugin data files. You can copy the files to share:

    mkdir /usr/share/rhythmbox/plugins/lastfmplaycount
    cp /usr/lib/rhythmbox/plugins/lastfmplaycount/* /usr/share/rhythmbox/plugins/lastfmplaycount

**Comment by BramBonne** [comment]
Closed thanks to @elzoona !
